name: .NET CD

on:
  push:
    branches: [ "releases/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release -p:Version="${{env.BUILD_VERSION}}"
    
    - name: Create Packages
      if: success() && github.event_name != 'pull_request'
      run: 'dotnet pack --configuration Release --include-symbols --include-source --no-build --no-restore --output "${{github.workspace}}/artifacts"'

    - name: Upload Artifacts
      if: success() && github.event_name != 'pull_request'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: artifacts
        path: '${{github.workspace}}/artifacts'

    - name: Publish Release Packages
      if: success() && startsWith(github.ref, 'refs/heads/main')
      run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY} --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}